### ISSUE TITLE
Reconnect when the websocket closes

### ISSUE THREAD

**Issue by ostrearium** [simolus3/hrana.dart#1]
What's the recommended way of reconnecting once the ws has closed (timeout)

**Comment by simolus3** [comment]
Do you mean with drift or with the raw `hrana` package? I don't think we can transparently recover from that yet, I'd just re-open the database.

In `package:hrana` version 0.2.0, you can use the `closed` getter on `Database` to obtain a future that resolves as soon as the database connection is closed, regardless of whether that was due to a `close()` call or because of a timeout/the server going down. So you can `whenComplete` that future to add a callback to run when that happens and re-open the database if necessary.
