### ISSUE TITLE
Embedded replica support

### ISSUE THREAD

**Issue by leccles1** [simolus3/hrana.dart#3]
Hey Simon, 

Incredible to see this package pop up, I'd spent the last couple weeks attempting to write my own Hrana client. I previously reached out on the sqlite3 package with regards to [libsql support ](https://github.com/simolus3/sqlite3.dart/issues/224).

I was wondering if [embedded replica](https://docs.turso.tech/features/embedded-replicas/introduction) support is on the horizon at all - I know the sync functionality isn't part of the Hrana specification so apologies if this question is out of the scope/relevance of this library

Thanks!

**Comment by simolus3** [comment]
This is not really in scope for either `package:sqlite3` or `package:hrana` - re-implementing the synchronization mechanism in Dart would just be very complex.

I think it would be interesting to explore a `package:libsql` that is mostly compatible with an async variant of `package:sqlite3` (using the same result types).
Given that libsql is only really accessible from Rust when one wants to benefit from native async support, we'd necessarily have to write a custom wrapper to access it from `dart:ffi` (awaiting stuff in rust and then using Dart send ports to communicate results). That's _possible_, but super annoying without native assets since it's a lot of work to ship precompiled native libraries at the moment.

If I find some time I can work on a prototype earlier, but I think this depends on native assets (https://github.com/dart-lang/sdk/issues/50565) to be distributable.

**Comment by leccles1** [comment]
Sorry for not checking back in here. It wasn't until I stumbled upon - https://github.com/dikatok/libsql_dart today, It looks like the author of this lib is using Flutter Rust Bridge which is cool to see. Then I remembered I opened this dialogue a few months ago and never replied!

Will mark this as closed - I should've done this a while back!
